export enum path {
  home = "/",
  apartments = "/catalog/flats",
  cottages = "/catalog/cottages",
  baths = "/catalog/baths",
  cars = "/catalog/cars",
  news = "news",
  detail = "/news/detail/:id",
  advert = "advert",
  rate = "rate",
  contacts = "contacts",
  catalog = "catalog/:type",
  notfound = "*",
  login = "login",
  registration = "registration",
}
